// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WMS_.Data;

#nullable disable

namespace WMS_.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    partial class WmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WMS_.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("AuditLogId");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Car", b =>
                {
                    b.Property<string>("CarId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_id");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacity");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_type");

                    b.HasKey("CarId");

                    b.ToTable("car");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("employee_name");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<string>("ShiftId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shift_id");

                    b.Property<string>("ZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zone_id");

                    b.HasKey("EmployeeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WMS_.Data.Entities.InboundOrder", b =>
                {
                    b.Property<string>("InboundOrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inbound_order_id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InboundOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("InboundSuplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("InboundOrderId");

                    b.ToTable("inbound_order");
                });

            modelBuilder.Entity("WMS_.Data.Entities.InboundOrderItem", b =>
                {
                    b.Property<string>("InboundOrderItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inbound_order_item_id");

                    b.Property<string>("InboundOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inbound_order_id");

                    b.Property<string>("SackId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sack_id");

                    b.HasKey("InboundOrderItemId");

                    b.HasIndex("InboundOrderId");

                    b.HasIndex("SackId");

                    b.ToTable("inbound_order_item");
                });

            modelBuilder.Entity("WMS_.Data.Entities.InventoryReservation", b =>
                {
                    b.Property<string>("ReservationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reservation_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("OutboundOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outbound_order_id");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<string>("SackId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sack_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("ReservationId");

                    b.HasIndex("OutboundOrderId");

                    b.HasIndex("SackId");

                    b.ToTable("inventory_reservation");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Location", b =>
                {
                    b.Property<string>("LocationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_name");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location_type");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("province_id");

                    b.HasKey("LocationId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("location");
                });

            modelBuilder.Entity("WMS_.Data.Entities.OutboundOrder", b =>
                {
                    b.Property<string>("OutboundOrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outbound_order_id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OutboundCustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer_name");

                    b.Property<string>("OutboundDestination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("destination");

                    b.Property<string>("OutboundOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("OutboundOrderId");

                    b.HasIndex("OutboundDestination");

                    b.ToTable("outbound_order");
                });

            modelBuilder.Entity("WMS_.Data.Entities.OutboundOrderItem", b =>
                {
                    b.Property<string>("OutboundOrderItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outbound_order_item_id");

                    b.Property<string>("OutboundOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outbound_order_id");

                    b.Property<string>("SackId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sack_id");

                    b.HasKey("OutboundOrderItemId");

                    b.HasIndex("OutboundOrderId");

                    b.HasIndex("SackId");

                    b.ToTable("outbound_order_item");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Pallet", b =>
                {
                    b.Property<string>("PalletId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pallet_id");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zone_id");

                    b.HasKey("PalletId");

                    b.HasIndex("ZoneId");

                    b.ToTable("pallet");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Province", b =>
                {
                    b.Property<string>("ProvinceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("province_id");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("province_name");

                    b.HasKey("ProvinceId");

                    b.ToTable("province");
                });

            modelBuilder.Entity("WMS_.Data.Entities.RoutingRule", b =>
                {
                    b.Property<string>("RuleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_id");

                    b.Property<string>("CDestinationID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("c_destination");

                    b.Property<string>("CurrentLocationID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_location");

                    b.Property<string>("NextHop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("next_hop");

                    b.HasKey("RuleId");

                    b.HasIndex("CDestinationID");

                    b.HasIndex("NextHop");

                    b.HasIndex(new[] { "CurrentLocationID", "CDestinationID" }, "unique_route")
                        .IsUnique();

                    b.ToTable("routing_rule");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Sack", b =>
                {
                    b.Property<string>("SackId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sack_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("PalletId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pallet_id");

                    b.Property<string>("SDestination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("s_destination");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TripId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trip_id");

                    b.Property<string>("ZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zone_id");

                    b.HasKey("SackId");

                    b.HasIndex("PalletId");

                    b.HasIndex("SDestination");

                    b.HasIndex("TripId");

                    b.HasIndex("ZoneId");

                    b.ToTable("sack");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Shift", b =>
                {
                    b.Property<string>("ShiftId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shift_id");

                    b.Property<TimeSpan>("EndAt")
                        .HasColumnType("interval")
                        .HasColumnName("end_at");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shift_name");

                    b.Property<TimeSpan>("StartAt")
                        .HasColumnType("interval")
                        .HasColumnName("start_at");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Trip", b =>
                {
                    b.Property<string>("TripId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trip_id");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("destination");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.HasKey("TripId");

                    b.HasIndex("CarId");

                    b.HasIndex("Destination");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Origin");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Zone", b =>
                {
                    b.Property<string>("ZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zone_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location_id");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone_name");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zone_type");

                    b.HasKey("ZoneId");

                    b.HasIndex("LocationId");

                    b.ToTable("zone");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Employee", b =>
                {
                    b.HasOne("WMS_.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("Shift");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("WMS_.Data.Entities.InboundOrderItem", b =>
                {
                    b.HasOne("WMS_.Data.Entities.InboundOrder", "InboundOrder")
                        .WithMany()
                        .HasForeignKey("InboundOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Sack", "Sack")
                        .WithMany()
                        .HasForeignKey("SackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InboundOrder");

                    b.Navigation("Sack");
                });

            modelBuilder.Entity("WMS_.Data.Entities.InventoryReservation", b =>
                {
                    b.HasOne("WMS_.Data.Entities.OutboundOrder", "OutboundOrder")
                        .WithMany()
                        .HasForeignKey("OutboundOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Sack", "Sack")
                        .WithMany()
                        .HasForeignKey("SackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutboundOrder");

                    b.Navigation("Sack");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Location", b =>
                {
                    b.HasOne("WMS_.Data.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("WMS_.Data.Entities.OutboundOrder", b =>
                {
                    b.HasOne("WMS_.Data.Entities.Location", "OutboundDestinationLocation")
                        .WithMany()
                        .HasForeignKey("OutboundDestination")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutboundDestinationLocation");
                });

            modelBuilder.Entity("WMS_.Data.Entities.OutboundOrderItem", b =>
                {
                    b.HasOne("WMS_.Data.Entities.OutboundOrder", "OutboundOrder")
                        .WithMany()
                        .HasForeignKey("OutboundOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Sack", "Sack")
                        .WithMany()
                        .HasForeignKey("SackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutboundOrder");

                    b.Navigation("Sack");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Pallet", b =>
                {
                    b.HasOne("WMS_.Data.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("WMS_.Data.Entities.RoutingRule", b =>
                {
                    b.HasOne("WMS_.Data.Entities.Location", "CDestination")
                        .WithMany()
                        .HasForeignKey("CDestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Location", "NextHopLocation")
                        .WithMany()
                        .HasForeignKey("NextHop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CDestination");

                    b.Navigation("CurrentLocation");

                    b.Navigation("NextHopLocation");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Sack", b =>
                {
                    b.HasOne("WMS_.Data.Entities.Pallet", "Pallet")
                        .WithMany()
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WMS_.Data.Entities.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("SDestination")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WMS_.Data.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DestinationLocation");

                    b.Navigation("Pallet");

                    b.Navigation("Trip");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Trip", b =>
                {
                    b.HasOne("WMS_.Data.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("Destination")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS_.Data.Entities.Location", "OriginLocation")
                        .WithMany()
                        .HasForeignKey("Origin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("DestinationLocation");

                    b.Navigation("Employee");

                    b.Navigation("OriginLocation");
                });

            modelBuilder.Entity("WMS_.Data.Entities.Zone", b =>
                {
                    b.HasOne("WMS_.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
