<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>WMS-</RootNamespace>
        <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="obj\Debug\net9.0\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="obj\Debug\net9.0\WMS-.AssemblyInfoInputs.cache" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
    </ItemGroup>

</Project>
